version: '3.1'
services:
  live-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Shanghai
      - GIN_MODE=release
    container_name: live-server
    ports:
      - 5666:5666