name: Build and Upload Release Binaries

on:
  release:
    types: [published]

jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.2

    - name: Run build script
      run: ./build.sh

    - name: Upload binaries to release
      env:
        UPLOAD_URL: ${{ github.event.release.upload_url }}
      run: |
        for file in ./dist/*; do
          echo "Uploading $file..."
          curl -sSL \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @"$file" \
            "$UPLOAD_URL?name=$(basename "$file")"
        done

    - name: Clean up dist directory
      run: rm -rf ./dist
