name: Build and Upload Release Binaries

on:
  release:
    types: [published]

jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.2

    - name: Run build script
      run: ./build.sh

    - name: List files for upload
      id: list_files
      run: |
        # 列出 dist 目录中的文件，并将其保存为 workflow output
        for file in dist/*; do
          echo "::append-output name=files::$file"
        done

    # 使用 matrix 策略逐个上传文件
    - name: Upload each binary to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ matrix.file }}
        asset_name: ${{ matrix.file }}
        asset_content_type: application/octet-stream
      strategy:
        matrix:
          file: ${{ fromJSON(steps.list_files.outputs.files) }}

    - name: Clean up dist directory
      run: rm -rf ./dist
